services:
    # Laravel PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        expose:
            - "9000" # Expose PHP-FPM internally for Nginx
        networks:
            - app-network
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=pgsql
            - DB_PORT=5432
            - DB_DATABASE=vouchermoney
            - DB_USERNAME=postgres
            - DB_PASSWORD=123123123
            - REDIS_HOST=redis

    # Nginx Service to act as reverse proxy
    nginx:
        image: nginx:alpine
        container_name: nginx_server
        restart: always
        ports:
            - "8080:80" # Nginx will serve on port 8080
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    # PostgreSQL Service
    pgsql:
        image: postgres:15
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_DB: vouchermoney
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123123123
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

    # Redis Service
    redis:
        image: redis:alpine
        container_name: redis_cache
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
        driver: local
